global:
  scrape_interval: 30s
  scrape_timeout: 30s

scrape_configs:
  - job_name: netcap
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["netcap-vmagent:7777"]
  - job_name: "node-stats"
    metrics_path: /metrics
    static_configs:
      - targets: ["nodestats:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "sflow-rt-analyzer"
    metrics_path: /prometheus/analyzer/txt
    static_configs:
      - targets: ["sflow-vmagent:8008"]
  - job_name: "sflow-rt-metrics"
    metrics_path: /prometheus/metrics/ALL/ALL/txt
    static_configs:
      - targets: ["sflow-vmagent:8008"]
    metric_relabel_configs:
      - source_labels: ["agent", "datasource"]
        separator: ":"
        target_label: instance
  - job_name: "sflow-rt-countries"
    metrics_path: /app/prometheus/scripts/export.js/flows/ALL/txt
    static_configs:
      - targets: ["sflow-vmagent:8008"]
    params:
      metric: ["sflow_country_bps"]
      key: ["null:[country:ipsource:both]:unknown","null:[country:ipdestination:both]:unknown"]
      label: ["src","dst"]
      value: ["bytes"]
      scale: ["8"]
      aggMode: ["sum"]
      minValue: ["1000"]
      maxFlows: ["100"]