apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    orgId: 1
    editable: false
    jsonData:
      timeInterval: 10s
  - name: loki
    access: proxy
    type: loki
    url: http://loki:3100
    isDefault: false
    database: ''
    user: ''
    password: ''
    basicAuth: false
    id: 1
    orgId: 1
    readOnly: false
    jsonData:
      keepCookies: []