version: "3.8"
services:
  netcap:
    image: dreadl0ck/netcap:alpine-v0.5.9
    container_name: netcap
    restart: unless-stopped
    network_mode: host
    expose:
      - 7777
    labels:
      org.label-schema.group: "net-capture"
    volumes:
      - type: bind
        source: /capture/netcap
        target: /var/log/netcap
  pmercury:
    build:
      context: ./docker/pmercury
      dockerfile: Dockerfile
      labels:
        - "com.example.description=Labeled SSL/TLS Signatures"
    image: pmercury
    container_name: pmercury
    restart: "no"
    network_mode: host
    volumes:
      - type: bind
        source: /var/log/pmercury
        target: /output
    labels:
      org.label-schema.group: "net-capture"
    command: ["-c", "eth1", "-d", "/resources/fingerprint-db.json.gz", "-f", "/output/pmercury.json", "-a", "-w", "-x", "-e"]
  sflow-collector:
    image: sflow/host-sflow
    container_name: host-sflow
    restart: unless-stopped
    network_mode: host
    environment:
      - COLLECTOR=sflow-prometheus
      - NET=eth1
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock:ro
    labels:
      org.label-schema.group: "net-capture"
  check-ip:
    build:
      context: ./docker/checkip
      dockerfile: Dockerfile
    image: checkip:latest
    restart: "no"
    networks:
      - monitor-net
    volumes:
      - type: bind
        source: /var/log/checkip
        target: /output
    labels:
      org.label-schema.group: "net-capture"
  sflow-prometheus:
    image: sflow/prometheus
    container_name: sflow-prometheus
    restart: unless-stopped
    networks:
      - monitor-net
    expose:
      - 6343/udp
      - 8008
    labels:
      org.label-schema.group: "monitor"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./docker/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus-data
        target: /prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitor"
  nodestats:
    image: prom/node-exporter
    container_name: nodestats
    expose:
      - 9100
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "host-capture"
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: /
        target: /rootfs:ro
      - type: bind
        source: /var/run
        target: /var/run:rw
      - type: bind
        source: /sys
        target: /sys:ro
      - type: bind
        source: /var/lib/docker/
        target: /var/lib/docker:ro
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "host-capture"
  loki:
    image: grafana/loki:1.6.1
    container_name: loki
    expose:
      - 3100
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitor"
    volumes:
      - type: volume
        source: loki-data
        target: /loki
      - type: bind
        source: ./docker/loki/loki-config.yml
        target: /etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:1.6.1
    container_name: promtail
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitor"
    volumes:
      - type: bind
        source: /var/log/pmercury
        target: /var/log/pmercury
      - type: bind
        source: /var/log/checkip
        target: /var/log/checkip
      - type: bind
        source: ./docker/promtail/promtail-config.yml
        target: /etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
  grafana:
    build:
      context: ./docker/grafana
      dockerfile: Dockerfile
      args:
        - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel,simpod-json-datasource
    image: grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana
      - type: bind
        source: ./docker/grafana/grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./docker/grafana/resources
        target: /etc/grafana/provisioning
      - type: bind
        source: ./docker/grafana/resources/dashboards
        target: /etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitor"

volumes:
  grafana-data:
  prometheus-data:
  netcap-data:
  mercury-data:
  loki-data:

networks:
  monitor-net:
    driver: bridge