server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            timeadded: added_to_otx
            src_ip: src_ip
            dst_ip: dst_ip
            ip_status: ip_status
      - labels:
          job: checkip
      - regex:
          expression: "^.* ip_status=(?P<ip_status>.?) .*$"
      - metrics:
          suspect_ip:
            type: Counter
            description: "Suspect IP"
            source: ip_status
            config:
              value: Suspect
              action: inc
          not_suspect_ip:
            type: Counter
            description: "Good IP"
            source: ip_status
            config:
              value: Good
              action: inc
    static_configs:
      - targets:
          - localhost
        labels:
          job: checkip
          __path__: /var/log/checkip/*.log

  - job_name: mercury_tls
    pipeline_stages:
      - json:
          expressions:
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            timestamp: event_start
            fingerprints:
            tls:
      - json:
          expressions:
            tls:
          source: fingerprints
      - json:
          expressions:
            server_name:
          source: tls
      - labels:
          job: mercury_tls
    static_configs:
      - targets:
          - localhost
        labels:
          job: pmercury
          __path__: /var/log/pmercury/tls.log*

  - job_name: mercury_tls_server
    pipeline_stages:      
      - json:
          expressions:
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            timestamp: event_start
            fingerprints:
      - json:
          expressions:
            tls_server:
          source: fingerprints
      - labels:
          job: mercury_tls_server
    static_configs:
      - targets:
          - localhost
        labels:
          job: pmercury
          __path__: /var/log/pmercury/tls_server.log*