server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: checkip
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            timeadded: added_to_otx
            src_ip: src_ip
            dst_ip: dst_ip
            ip_status: ip_status
            
      - labels:
          job: checkip
      - metrics:
          suspect_ip:
            type: Counter
            description: "Suspect IP"
            source: ip_status
            config:
              value: Suspect
              action: inc
          not_suspect_ip:
            type: Counter
            description: "Good IP"
            source: ip_status
            config:
              value: Good
              action: inc
    static_configs:
      - targets:
          - localhost
        labels:
          job: checkip
          __path__: /var/log/checkip/checkip.json*

  - job_name: pmercury_tls
    pipeline_stages:
      - json:
          expressions:
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            timestamp: event_start
            fingerprints:
            tls:
      - json:
          expressions:
            tls_fp: tls
          source: fingerprints
      - json:
          expressions:
            server_name:
          source: tls
      - labels:
          src_ip:
          dst_ip:
          src_port:
          dst_port:
          timestamp:
          tls_fp:
          server_name:
    static_configs:
      - targets:
          - localhost
        labels:
          job: pmercury_tls
          __path__: /var/log/pmercury/tls_pmercury.json*

  - job_name: pmercury_tls_server
    pipeline_stages:      
      - json:
          expressions:
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            timestamp: event_start
            fingerprints:
      - json:
          expressions:
            tls_server_fp: tls_server
          source: fingerprints
      - labels:
          src_ip:
          dst_ip:
          src_port:
          dst_port:
          timestamp:
          tls_server_fp:
    static_configs:
      - targets:
          - localhost
        labels:
          job: pmercury_tls_server
          __path__: /var/log/pmercury/tls_server_pmercury.json*