server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: netcap-tls-client
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            src_ip: src_ip
            dst_ip: dst_ip
      - labels:
          job: tls-client
    static_configs:
      - targets:
          - localhost
        labels:
          job: tls-client
          __path__: /var/log/netcap/tlsclient.log*

  - job_name: netcap-tls-server
    pipeline_stages:
      - json:
          expressions:
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            timestamp: event_start
            fingerprints:
            tls:
      - json:
          expressions:
            tls:
          source: fingerprints
      - json:
          expressions:
            server_name:
          source: tls
      - labels:
          job: tls-server
    static_configs:
      - targets:
          - localhost
        labels:
          job: tls-server
          __path__: /var/log/netcap/tlsserver.log*

  - job_name: netcap-network-flow
    pipeline_stages:      
      - json:
          expressions:
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            timestamp: event_start
            fingerprints:
      - json:
          expressions:
            tls_server:
          source: fingerprints
      - labels:
          job: network-flow
    static_configs:
      - targets:
          - localhost
        labels:
          job: network-flow
          __path__: /var/log/pmercury/tls_server.log*