server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: netcap_tls_client_hello
    pipeline_stages:
      - json:
          expressions:
            src_ip: SrcIP
            dst_ip: DstIP
            src_port: SrcPort
            dst_port: DstPort
            timestamp:
              source: Timestamp
              format: UnixMs
            fingerprints: Ja3
            server_name: SNI
            cipher_suites: CipherSuites
            signature_algorithms: SignatureAlgs
            extensions: Extensions
            message_length: MessageLen
            handshake_length: HandshakeLen
            handshake_version: HandshakeVersion
      - labels:
          src_ip:
          dst_ip:
          src_port:
          dst_port:
          timestamp:
          fingerprints:
          server_name:
          cipher_suites:
          signature_algorithms:
          extensions:
          message_length:
          handshake_length:
          handshake_version:
    static_configs:
      - targets:
          - localhost
        labels:
          job: netcap_tls_client_hello
          __path__: /var/log/netcap/TLSClientHello.json

  - job_name: netcap_tls_server_hello
    pipeline_stages:      
      - json:
          expressions:
            src_ip: SrcIP
            dst_ip: DstIP
            src_port: SrcPort
            dst_port: DstPort
            timestamp:
              source: Timestamp
              format: UnixMs
            fingerprints: Ja3s
            src_mac: SrcMAC
            dst_mac: DstMAC
            extensions: Extensions
            cipher_suite: CipherSuite
      - labels:
          src_ip:
          dst_ip:
          src_port:
          dst_port:
          timestamp:
          fingerprints:
          src_mac:
          dst_mac:
          extensions:
          cipher_suite:
    static_configs:
      - targets:
          - localhost
        labels:
          job: netcap_tls_server_hello
          __path__: /var/log/netcap/TLSServerHello.json

  - job_name: netcap_dns
    pipeline_stages:
      - json:
          expressions:
            timestamp:
              source: Timestamp
              format: UnixMs
            questions: Questions
            src_ip: SrcIP
            dst_ip: DstIP
            src_port: SrcPort
            dst_port: DstPort
      - json:
          expressions:
            name: Name
          source: questions
      - labels:
          timestamp:
          src_ip:
          dst_ip:
          src_port:
          dst_port:
          name:
    static_configs:
      - targets:
          - localhost
        labels:
          job: netcap_dns
          __path__: /var/log/netcap/DNS.json

  - job_name: netcap_ethernet
    pipeline_stages:
      - json:
          expressions:
            timestamp:
              source: Timestamp
              format: UnixMs
            src_mac: SrcMAC
            dst_mac: DstMAC
            ether_type: EthernetType
            payload_size: PayloadSize
      - labels:
          timestamp:
          src_mac:
          dst_mac:
          ether_type:
          payload_size:
    static_configs:
      - targets:
          - localhost
        labels:
          job: netcap_ethernet
          __path__: /var/log/netcap/Ethernet.json

  - job_name: netcap_connection
    pipeline_stages:
      - json:
          expressions:
            timestamp:
              source: TimestampFirst
              format: UnixMs
            timestamp_end: TimestampLast
            link_protocol: LinkProto
            network_protocol: NetworkProto
            transport_protocol: TransportProto
            application_protocol: ApplicationProto
            src_mac: SrcMAC
            dst_mac: DstMAC
            src_ip: SrcIP
            dst_ip: DstIP
            src_port: SrcPort
            dst_port: DstPort
            packets: NumPackets
            total_size: TotalSize
      - labels:
        timestamp:
        timestamp_end:
        link_protocol:
        network_protocol:
        transport_protocol:
        application_protocol:
        src_mac:
        dst_mac:
        src_ip:
        dst_ip:
        src_port:
        dst_port:
        packets:
        total_size:
    static_configs:
      - targets:
          - localhost
        labels:
          job: netcap_connection
          __path__: /var/log/netcap/Connection.json