server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: checkip
    pipeline_stages:
      - json:
          expressions:
            report_db: report_db
            ip_addr: ip_addr
            latitude: latitude
            longitude: longitude
            urls: urls
            first_reported: first_seen
            last_reported: last_seen
            ip_status: ip_status
      - timestamp:
          source: query_date
          format: "2020-11-05T01:40:27.942496"
      - labels:
          timestamp:
          report_db:
          ip_addr:
          latitude:
          longitude:
          first_reported:
          last_reported:
          ip_status:

      - metrics:
          ip_status:
            type: Histogram
            description: "Suspect IPs"
            source: ip_status
            config:
              value: potentially_malicious
              action: inc
      - metrics:
          ip_status:
            type: Histogram
            description: "Good IPs"
            source: ip_status
            config:
              value: likely_benign
              action: inc
      - metrics:
          ip_status:
            type: Counter
            description: "Unknown IPs"
            source: ip_status
            config:
              value: potentially_malicious_but_offline
              action: inc
              
    static_configs:
      - targets:
          - localhost
        labels:
          job: checkip
          __path__: /var/log/checkip/output.json

  - job_name: pmercury_tls
    pipeline_stages:
      - json:
          expressions:
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            fingerprints:
            tls:
      - timestamp:
          source: event_start
          format: "1604540427.5977054"
      - json:
          expressions:
            tls_fp: tls
          source: fingerprints
      - json:
          expressions:
            server_name:
          source: tls
      - labels:
          timestamp:
          src_ip:
          dst_ip:
          src_port:
          dst_port:
          tls_fp:
          server_name:
    static_configs:
      - targets:
          - localhost
        labels:
          job: pmercury_tls
          __path__: /var/log/pmercury/tls_pmercury.json

  - job_name: pmercury_tls_server
    pipeline_stages:      
      - json:
          expressions:
            src_ip: src_ip
            dst_ip: dst_ip
            src_port: src_port
            dst_port: dst_port
            fingerprints:
      - timestamp:
          source: event_start
          format: "1604540427.5977054"
      - json:
          expressions:
            tls_server_fp: tls_server
          source: fingerprints
      - labels:
          timestamp:
          src_ip:
          dst_ip:
          src_port:
          dst_port:
          tls_server_fp:
    static_configs:
      - targets:
          - localhost
        labels:
          job: pmercury_tls_server
          __path__: /var/log/pmercury/tls_server_pmercury.json